---
- name: Setup after new install
  hosts: proxmoxmain
  gather_facts: true
  become: true

  roles:
    - update_repo
    # - wifi_setup
    - create_sudo_user
    - generate_ssh_localhost
    - basics

